package exception

const (
	USER_NOT_FOUND        = "USER_NOT_FOUND"
	USER_ALREADY_EXISTS   = "USER_ALREADY_EXISTS"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	INVALID_CREDENTIALS    = "INVALID_CREDENTIALS"
)
